theme: jekyll-theme-minimal
title: Hacktoberfest Mauritius 2019
logo: https://github.com/Front-End-Coders-Mauritius/hacktoberfestmu-2019/raw/master/assets/hacktoberfest_logo.png
description: Hacktoberfest is an annual month-long event held in the month of October presented this year bt Digital Ocean and DEV. This is a month to celebrate and encourage developers to get involved and contribute to open source projects.
